# Generated by Django 3.1 on 2021-01-25 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.TextField()),
                ('variation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.TextField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_identifier', models.TextField()),
                ('breaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.breaker')),
            ],
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField()),
                ('serial_base', models.IntegerField(null=True)),
                ('name', models.TextField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.set')),
            ],
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField(null=True)),
                ('auto', models.BooleanField()),
                ('damage', models.TextField(null=True)),
                ('timestamp', models.TextField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.checklist')),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.subset')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.video')),
            ],
        ),
    ]
