# Generated by Django 3.1.7 on 2021-03-26 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.TextField()),
                ('mlb_licensed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.TextField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('variation', models.TextField(blank=True)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_identifier', models.TextField(unique=True)),
                ('comment', models.TextField(blank=True)),
                ('date', models.DateTimeField(null=True)),
                ('breaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.breaker')),
            ],
        ),
        migrations.CreateModel(
            name='Subset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.TextField(blank=True)),
                ('serial_base', models.IntegerField(blank=True, null=True)),
                ('name', models.TextField()),
                ('checklist_size', models.IntegerField(blank=True, null=True)),
                ('shorthand', models.CharField(blank=True, max_length=16)),
                ('multi_base', models.BooleanField(default=False)),
                ('multi_base_numbered', models.BooleanField(default=False)),
                ('autographed', models.BooleanField(default=False)),
                ('comc_color', models.TextField(blank=True, default='')),
                ('comc_color_blank', models.BooleanField(blank=True, default=False)),
                ('comc_name', models.TextField(blank=True, default='')),
                ('comc_name_blank', models.BooleanField(blank=True, default=False)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.set')),
            ],
            options={
                'ordering': ('-serial_base',),
                'unique_together': {('set', 'name', 'serial_base', 'color')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('packs_per_box', models.IntegerField()),
                ('cards_per_pack', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.set')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(blank=True, max_length=12)),
                ('serial_base', models.IntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.subject')),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.subset')),
            ],
            options={
                'ordering': ('subject__name', 'subset__name'),
            },
        ),
    ]
