# Generated by Django 3.1 on 2021-01-26 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='mlb_licensed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='variation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subset',
            name='color',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subset',
            name='serial_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
