# Generated by Django 3.1.7 on 2021-03-31 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0002_auto_20210326_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('card_number', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='subset',
            name='card_number_critical',
        ),
        migrations.AddField(
            model_name='card',
            name='variation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='card_set.variation'),
        ),
    ]
