# Generated by Django 3.1 on 2021-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0002_auto_20210126_0143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subset',
            options={'ordering': ('serial_base',)},
        ),
        migrations.AddField(
            model_name='subset',
            name='checklist_size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pull',
            name='damage',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pull',
            name='serial',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pull',
            name='timestamp',
            field=models.TextField(blank=True),
        ),
    ]
