# Generated by Django 3.1 on 2021-01-26 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0003_auto_20210126_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='auto',
        ),
    ]
