# Generated by Django 3.1 on 2021-01-26 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0004_remove_pull_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'ordering': ('player_name',)},
        ),
    ]
