# Generated by Django 3.1 on 2021-01-26 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0005_auto_20210126_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='boxes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
