# Generated by Django 3.1 on 2021-01-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0006_video_boxes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subset',
            options={'ordering': ('-serial_base',)},
        ),
        migrations.AddField(
            model_name='subset',
            name='shorthand',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
    ]
