# Generated by Django 3.1 on 2021-01-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0007_auto_20210126_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subset',
            name='shorthand',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('packs_per_box', models.IntegerField()),
                ('cards_per_pack', models.IntegerField()),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.set')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.product')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.video')),
            ],
        ),
        migrations.AddField(
            model_name='pull',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card_set.box'),
        ),
    ]
