# Generated by Django 3.1 on 2021-01-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0008_auto_20210126_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='boxes',
        ),
    ]
