# Generated by Django 3.1 on 2021-01-29 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0010_auto_20210128_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subset',
            name='checklist_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
