# Generated by Django 3.1 on 2021-01-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0011_auto_20210129_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
