# Generated by Django 3.1 on 2021-01-31 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0012_video_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Checklist',
            new_name='Player',
        ),
    ]
