# Generated by Django 3.1 on 2021-02-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0013_auto_20210131_0408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subset',
            unique_together={('set', 'name', 'serial_base', 'color')},
        ),
    ]
