# Generated by Django 3.1 on 2021-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0014_auto_20210203_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='timestamp',
            field=models.FloatField(blank=True),
        ),
    ]
