# Generated by Django 3.1 on 2021-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0015_auto_20210204_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pull',
            name='back_timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
