# Generated by Django 3.1 on 2021-02-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0016_pull_back_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
