# Generated by Django 3.1 on 2021-02-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0017_auto_20210204_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pull',
            old_name='timestamp',
            new_name='front_timestamp',
        ),
    ]
