# Generated by Django 3.1 on 2021-02-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0018_auto_20210204_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='scarcity_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
