# Generated by Django 3.1 on 2021-02-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0019_box_scarcity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='box',
            name='scarcity_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
