# Generated by Django 3.1 on 2021-02-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0020_auto_20210205_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
