# Generated by Django 3.1 on 2021-02-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0021_auto_20210206_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
