# Generated by Django 3.1 on 2021-02-09 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0022_auto_20210206_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=12)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.player')),
                ('subset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.subset')),
            ],
        ),
        migrations.AddField(
            model_name='pull',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card_set.card'),
        ),
    ]
