# Generated by Django 3.1 on 2021-02-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0023_auto_20210209_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pull',
            name='player',
        ),
        migrations.RemoveField(
            model_name='pull',
            name='subset',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
