# Generated by Django 3.1 on 2021-02-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0024_auto_20210210_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('variation', models.TextField(blank=True)),
                ('slug', models.SlugField()),
                ('rookie_year', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='card',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.subject'),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
