# Generated by Django 3.1 on 2021-02-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0025_auto_20210212_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='rookie_year',
        ),
        migrations.AddField(
            model_name='subset',
            name='multi_base',
            field=models.BooleanField(default=False),
        ),
    ]
