# Generated by Django 3.1 on 2021-02-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0026_auto_20210215_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='autographed',
            field=models.BooleanField(default=False),
        ),
    ]
