# Generated by Django 3.1 on 2021-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0027_subset_autographed'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='multi_base_numbered',
            field=models.BooleanField(default=False),
        ),
    ]
