# Generated by Django 3.1 on 2021-03-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0028_subset_multi_base_numbered'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='serial_base',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
