# Generated by Django 3.1 on 2021-03-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_set', '0031_auto_20210315_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='subset',
            name='comc_color_blank',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='subset',
            name='comc_name_blank',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
