# Generated by Django 3.1.7 on 2021-03-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card_set', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('scarcity_score', models.FloatField(blank=True, default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.product')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='card_set.video')),
            ],
            options={
                'db_table': 'card_set_box',
            },
        ),
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.TextField(blank=True)),
                ('front_timestamp', models.FloatField(blank=True, null=True)),
                ('back_timestamp', models.FloatField(blank=True, null=True)),
                ('damage', models.TextField(blank=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card_pull.box')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='card_set.card')),
            ],
            options={
                'db_table': 'card_set_pull',
            },
        ),
    ]
