# Generated by Django 3.1.7 on 2021-03-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_pull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='completly_indexed',
            field=models.BooleanField(default=True),
        ),
    ]
